// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trainova.Infrastructure.DataAccess;

#nullable disable

namespace Trainova.Infrastructure.DataAccess.Migrations
{
    [DbContext(typeof(TrainovaWriteDbContext))]
    [Migration("20260430004049_Init_3_7")]
    partial class Init_3_7
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Trainova.Domain.Common.AuditLogs.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("From")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRecovered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RecoveredAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("RecoveredByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("EntityId");

                    b.HasIndex("EntityName");

                    b.HasIndex("IsRecovered");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.Common.Outbox.EmailOutbox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSent")
                        .HasColumnType("bit");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("EmailOutboxes", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.FitnessStatus.MovementDistances.SessionMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("PlayerLoad")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("SprintsCount")
                        .HasColumnType("int");

                    b.Property<Guid>("TrainingSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TrainingSessionId");

                    b.ToTable("SessionMovements");
                });

            modelBuilder.Entity("Trainova.Domain.FitnessStatus.PhysicalCapacityTests.PhysicalCapacityTest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("CapacityTests");
                });

            modelBuilder.Entity("Trainova.Domain.MatchsManagement.ComputedFeatures.ComputedFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("ActionsPer90")
                        .HasColumnType("float");

                    b.Property<double>("ActivityDrop2ndHalf")
                        .HasColumnType("float");

                    b.Property<double>("AvgPositionX")
                        .HasColumnType("float");

                    b.Property<double>("AvgPositionY")
                        .HasColumnType("float");

                    b.Property<double>("AvgSpeed")
                        .HasColumnType("float");

                    b.Property<double>("BallRetentionRate")
                        .HasColumnType("float");

                    b.Property<double>("CarrySuccessRate")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("DefensiveValue")
                        .HasColumnType("float");

                    b.Property<double>("DistanceCovered")
                        .HasColumnType("float");

                    b.Property<double>("DribbleSuccessRate")
                        .HasColumnType("float");

                    b.Property<int>("FoulsCommitted")
                        .HasColumnType("int");

                    b.Property<int>("FoulsWon")
                        .HasColumnType("int");

                    b.Property<int>("HighIntensityActions")
                        .HasColumnType("int");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("OffensiveValue")
                        .HasColumnType("float");

                    b.Property<double>("PassAccuracy")
                        .HasColumnType("float");

                    b.Property<int>("PassesUnderPressure")
                        .HasColumnType("int");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("PositionDeviation")
                        .HasColumnType("float");

                    b.Property<double>("Ppda")
                        .HasColumnType("float");

                    b.Property<int>("PressureRegains")
                        .HasColumnType("int");

                    b.Property<int>("ProgressiveCarries")
                        .HasColumnType("int");

                    b.Property<int>("ProgressivePasses")
                        .HasColumnType("int");

                    b.Property<int>("RedCards")
                        .HasColumnType("int");

                    b.Property<double>("ShotAccuracy")
                        .HasColumnType("float");

                    b.Property<int>("ShotsOnTarget")
                        .HasColumnType("int");

                    b.Property<int>("SprintCount")
                        .HasColumnType("int");

                    b.Property<int>("TotalPasses")
                        .HasColumnType("int");

                    b.Property<int>("TotalPressures")
                        .HasColumnType("int");

                    b.Property<int>("TotalShots")
                        .HasColumnType("int");

                    b.Property<double>("TotalXg")
                        .HasColumnType("float");

                    b.Property<double>("VaepRating")
                        .HasColumnType("float");

                    b.Property<double>("XgPerShot")
                        .HasColumnType("float");

                    b.Property<int>("YellowCards")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId");

                    b.ToTable("ComputedFeatures", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.MatchsManagement.Events.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BodyPart")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<double?>("CarryEndX")
                        .HasColumnType("float");

                    b.Property<double?>("CarryEndY")
                        .HasColumnType("float");

                    b.Property<bool?>("CounterPress")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DribbleOutcome")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int?>("EventIndex")
                        .HasColumnType("int");

                    b.Property<string>("EventType")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<bool?>("IsProgressivePass")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("LocationX")
                        .HasColumnType("float");

                    b.Property<double?>("LocationY")
                        .HasColumnType("float");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Minute")
                        .HasColumnType("tinyint");

                    b.Property<double?>("PassAngle")
                        .HasColumnType("float");

                    b.Property<double?>("PassEndX")
                        .HasColumnType("float");

                    b.Property<double?>("PassEndY")
                        .HasColumnType("float");

                    b.Property<double?>("PassLength")
                        .HasColumnType("float");

                    b.Property<string>("PassOutcome")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("PredictedXg")
                        .HasColumnType("float");

                    b.Property<double?>("PressureDuration")
                        .HasColumnType("float");

                    b.Property<byte>("Second")
                        .HasColumnType("tinyint");

                    b.Property<bool?>("ShotAfterSetPiece")
                        .HasColumnType("bit");

                    b.Property<double?>("ShotEndX")
                        .HasColumnType("float");

                    b.Property<double?>("ShotEndY")
                        .HasColumnType("float");

                    b.Property<string>("ShotOutcome")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("ShotTechnique")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<double?>("ShotXg")
                        .HasColumnType("float");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("Timestamp")
                        .HasColumnType("time");

                    b.Property<bool?>("UnderPressure")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.MatchsManagement.Lineups.Lineup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsStarter")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MinutesPlayed")
                        .HasColumnType("int");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StartingPosition")
                        .HasColumnType("int");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("StartingPosition");

                    b.HasIndex("TeamId");

                    b.ToTable("Lineups", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.MatchsManagement.Matches.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("AwayScore")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("AwayTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("HomeScore")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("MatchDate")
                        .HasColumnType("date");

                    b.Property<int>("MatchWeek")
                        .HasColumnType("int");

                    b.Property<string>("Referee")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Stadium")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("MatchDate");

                    b.ToTable("Matches", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.MatchsManagement.Videos.MatchVideo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ObjectStoregeProviderId")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("RelatedMatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.HasKey("Id");

                    b.HasIndex("RelatedMatchId");

                    b.ToTable("MatchVideos", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.MedicalStatus.Injuries.Injury", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan?>("AverageRecoveryTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1200)
                        .HasColumnType("nvarchar(1200)");

                    b.Property<string>("InjuryType")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("InjuryType");

                    b.ToTable("Injuries", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.MedicalStatus.PlayerInjuries.PlayerInjury", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BodyPart")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Cause")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ExpectedReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HappendAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InjuryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsNew")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(1200)
                        .HasColumnType("nvarchar(1200)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SevertiyGrade")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("InjuryId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("Status");

                    b.ToTable("PlayerInjuries", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.MedicalStatus.RecoveryPlans.RecoveryPlanPhase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Activities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1200)
                        .HasColumnType("nvarchar(1200)");

                    b.Property<DateTime>("From")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte>("Order")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("PlayerInjuryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("To")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlayerInjuryId")
                        .IsUnique();

                    b.ToTable("RecoveryPlanPhases", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.Profiles.Players.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentMainPosition")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfEnrolment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MedicalStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("OtherAvailablePositions")
                        .HasColumnType("int");

                    b.Property<decimal>("PerformanceLevel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PlayerNumber")
                        .HasColumnType("int");

                    b.Property<string>("TShirtName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Players", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.Profiles.ScoutingCandidates.ScoutingCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentMainPosition")
                        .HasColumnType("int");

                    b.Property<Guid?>("CurrentTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<float>("InjuryRisk")
                        .HasColumnType("real");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MedecalStatus")
                        .HasColumnType("int");

                    b.Property<int>("OtherAvailablePositions")
                        .HasColumnType("int");

                    b.Property<decimal>("PerformanceLevel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<float>("PerformanceScore")
                        .HasColumnType("real");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrentTeamId");

                    b.ToTable("ScoutingCandidates", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.Profiles.TeamsStaff.TeamStaff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContractFilesLink")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InsuranceFilesLink")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("TeamStaffs", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.SeasonsAnalyses.ModelScores.ModelScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("BehavioralScore")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("MovementScore")
                        .HasColumnType("float");

                    b.Property<double>("OverallScore")
                        .HasColumnType("float");

                    b.Property<double>("PassingScore")
                        .HasColumnType("float");

                    b.Property<double>("PercentileInLeague")
                        .HasColumnType("float");

                    b.Property<double>("PercentileInPosition")
                        .HasColumnType("float");

                    b.Property<double>("PercentileInTeam")
                        .HasColumnType("float");

                    b.Property<string>("PerformanceTrend")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<double>("PhysicalScore")
                        .HasColumnType("float");

                    b.Property<string>("PlayerCluster")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("PositionFitScore")
                        .HasColumnType("float");

                    b.Property<double>("PositioningScore")
                        .HasColumnType("float");

                    b.Property<double>("PressingScore")
                        .HasColumnType("float");

                    b.Property<double>("ShootingScore")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId");

                    b.ToTable("ModelScores", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.SeasonsAnalyses.PositionBenchmarks.PositionBenchmark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("AvgDistanceCovered")
                        .HasColumnType("float");

                    b.Property<double?>("AvgPassAccuracy")
                        .HasColumnType("float");

                    b.Property<double?>("AvgPressures")
                        .HasColumnType("float");

                    b.Property<double?>("AvgProgressivePasses")
                        .HasColumnType("float");

                    b.Property<double?>("AvgVaep")
                        .HasColumnType("float");

                    b.Property<double?>("AvgXg")
                        .HasColumnType("float");

                    b.Property<int>("CompetitionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PositionGroup")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.Property<double?>("WeightBehavioral")
                        .HasColumnType("float");

                    b.Property<double?>("WeightMovement")
                        .HasColumnType("float");

                    b.Property<double?>("WeightPassing")
                        .HasColumnType("float");

                    b.Property<double?>("WeightPhysical")
                        .HasColumnType("float");

                    b.Property<double?>("WeightPositioning")
                        .HasColumnType("float");

                    b.Property<double?>("WeightPressing")
                        .HasColumnType("float");

                    b.Property<double?>("WeightShooting")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("SeasonId");

                    b.ToTable("PositionBenchmarks", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.SeasonsAnalyses.Seasons.Competition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompetitionName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CountryName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SeasonName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("Competitions", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.SeasonsAnalyses.Teams.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TeamName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Teams", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.TrainingSessionsAccessibility.AccessPolicies.AccessPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PolicyName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("AccessPolicies", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.TrainingSessionsAccessibility.AccessPolicies.UserAccessPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccessPoliciesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttendanceState")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DoneScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TrainingSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccessPoliciesId");

                    b.HasIndex("TrainingSessionId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAccessPolicies", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.TrainingSessionsAccessibility.Plans.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccessPolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlanGoul")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccessPolicyId");

                    b.ToTable("Plans", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.TrainingSessionsAccessibility.TrainingSessions.TrainingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AccessPolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("HappenedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Place")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SessionState")
                        .HasColumnType("int");

                    b.Property<string>("TrainingSessionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccessPolicyId");

                    b.HasIndex("PlanId");

                    b.ToTable("TrainingSessions");
                });

            modelBuilder.Entity("Trainova.Domain.UserAuth.Roles.Role", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Trainova.Domain.UserAuth.UserRoles.UserRole", b =>
                {
                    b.Property<byte>("RoleId")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("RoleId1")
                        .HasColumnType("tinyint");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("RoleId1");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.UserAuth.UserTokens.UserToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<int?>("RevokeCause")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.UserAuth.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsTFAEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ShowName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("TFAEnabledAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TeamStaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("_passwordHash")
                        .IsRequired()
                        .HasMaxLength(2400)
                        .HasColumnType("nvarchar(2400)")
                        .HasColumnName("PasswordHash");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.HasIndex("TeamStaffId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Trainova.Domain.FitnessStatus.MovementDistances.SessionMovement", b =>
                {
                    b.HasOne("Trainova.Domain.Profiles.Players.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Trainova.Domain.TrainingSessionsAccessibility.TrainingSessions.TrainingSession", "TrainingSession")
                        .WithMany()
                        .HasForeignKey("TrainingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Trainova.Domain.FitnessStatus.MovementDistances.Distance", "Distance", b1 =>
                        {
                            b1.Property<Guid>("SessionMovementId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("HighSpeedRunDistance")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("HighSpeedRunDistance");

                            b1.Property<decimal>("RunDistance")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("RunDistance");

                            b1.Property<decimal>("TotalDistance")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("TotalDistance");

                            b1.Property<decimal>("WalkDistance")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("WalkDistance");

                            b1.HasKey("SessionMovementId");

                            b1.ToTable("SessionMovements");

                            b1.WithOwner()
                                .HasForeignKey("SessionMovementId");
                        });

                    b.OwnsOne("Trainova.Domain.FitnessStatus.MovementDistances.Speed", "Speed", b1 =>
                        {
                            b1.Property<Guid>("SessionMovementId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("AverageSpeed")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("AverageSpeed");

                            b1.Property<decimal>("MaxSpeed")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("MaxSpeed");

                            b1.Property<decimal>("PeakAcceleration")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("PeakAcceleration");

                            b1.HasKey("SessionMovementId");

                            b1.ToTable("SessionMovements");

                            b1.WithOwner()
                                .HasForeignKey("SessionMovementId");
                        });

                    b.Navigation("Distance");

                    b.Navigation("Player");

                    b.Navigation("Speed");

                    b.Navigation("TrainingSession");
                });

            modelBuilder.Entity("Trainova.Domain.FitnessStatus.PhysicalCapacityTests.PhysicalCapacityTest", b =>
                {
                    b.OwnsOne("Trainova.Domain.FitnessStatus.PhysicalCapacityTests.AerobicCapacityTest", "AerobicCapacityTest", b1 =>
                        {
                            b1.Property<Guid>("PhysicalCapacityTestId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("MaximumOxygenConsumption")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<int>("YoYoIntermittentRecoveryLevel1Distance")
                                .HasColumnType("int");

                            b1.Property<int>("YoYoIntermittentRecoveryLevel2Distance")
                                .HasColumnType("int");

                            b1.HasKey("PhysicalCapacityTestId");

                            b1.ToTable("CapacityTests");

                            b1.WithOwner()
                                .HasForeignKey("PhysicalCapacityTestId");
                        });

                    b.OwnsOne("Trainova.Domain.FitnessStatus.PhysicalCapacityTests.ExplosivePowerTest", "ExplosivePowerTest", b1 =>
                        {
                            b1.Property<Guid>("PhysicalCapacityTestId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("CountermovementJumpHeight")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("ReactiveStrengthIndex")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("PhysicalCapacityTestId");

                            b1.ToTable("CapacityTests");

                            b1.WithOwner()
                                .HasForeignKey("PhysicalCapacityTestId");
                        });

                    b.OwnsOne("Trainova.Domain.FitnessStatus.PhysicalCapacityTests.SprintTest", "SprintTest", b1 =>
                        {
                            b1.Property<Guid>("PhysicalCapacityTestId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Time10Meters")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("Time30Meters")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("PhysicalCapacityTestId");

                            b1.ToTable("CapacityTests");

                            b1.WithOwner()
                                .HasForeignKey("PhysicalCapacityTestId");
                        });

                    b.Navigation("AerobicCapacityTest")
                        .IsRequired();

                    b.Navigation("ExplosivePowerTest")
                        .IsRequired();

                    b.Navigation("SprintTest")
                        .IsRequired();
                });

            modelBuilder.Entity("Trainova.Domain.MatchsManagement.Matches.Match", b =>
                {
                    b.HasOne("Trainova.Domain.TrainingSessionsAccessibility.TrainingSessions.TrainingSession", "TrainingSession")
                        .WithOne("Match")
                        .HasForeignKey("Trainova.Domain.MatchsManagement.Matches.Match", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingSession");
                });

            modelBuilder.Entity("Trainova.Domain.MedicalStatus.PlayerInjuries.PlayerInjury", b =>
                {
                    b.HasOne("Trainova.Domain.MedicalStatus.Injuries.Injury", "Injury")
                        .WithMany("PlayerInjuries")
                        .HasForeignKey("InjuryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trainova.Domain.Profiles.Players.Player", "Player")
                        .WithMany("PlayerInjuries")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Injury");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Trainova.Domain.MedicalStatus.RecoveryPlans.RecoveryPlanPhase", b =>
                {
                    b.HasOne("Trainova.Domain.MedicalStatus.PlayerInjuries.PlayerInjury", "PlayerInjury")
                        .WithOne()
                        .HasForeignKey("Trainova.Domain.MedicalStatus.RecoveryPlans.RecoveryPlanPhase", "PlayerInjuryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerInjury");
                });

            modelBuilder.Entity("Trainova.Domain.Profiles.Players.Player", b =>
                {
                    b.HasOne("Trainova.Domain.UserAuth.Users.User", "User")
                        .WithOne()
                        .HasForeignKey("Trainova.Domain.Profiles.Players.Player", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Trainova.Domain.Profiles.TeamsStaff.TeamStaff", b =>
                {
                    b.HasOne("Trainova.Domain.UserAuth.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Trainova.Domain.TrainingSessionsAccessibility.AccessPolicies.UserAccessPolicy", b =>
                {
                    b.HasOne("Trainova.Domain.TrainingSessionsAccessibility.AccessPolicies.AccessPolicy", "AccessPolicy")
                        .WithMany("PolicyUsers")
                        .HasForeignKey("AccessPoliciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trainova.Domain.TrainingSessionsAccessibility.TrainingSessions.TrainingSession", null)
                        .WithMany("UserAccessPolicies")
                        .HasForeignKey("TrainingSessionId");

                    b.HasOne("Trainova.Domain.UserAuth.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessPolicy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Trainova.Domain.TrainingSessionsAccessibility.Plans.Plan", b =>
                {
                    b.HasOne("Trainova.Domain.TrainingSessionsAccessibility.AccessPolicies.AccessPolicy", "AccessPolicy")
                        .WithMany()
                        .HasForeignKey("AccessPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessPolicy");
                });

            modelBuilder.Entity("Trainova.Domain.TrainingSessionsAccessibility.TrainingSessions.TrainingSession", b =>
                {
                    b.HasOne("Trainova.Domain.TrainingSessionsAccessibility.AccessPolicies.AccessPolicy", "AccessPolicy")
                        .WithMany()
                        .HasForeignKey("AccessPolicyId");

                    b.HasOne("Trainova.Domain.TrainingSessionsAccessibility.Plans.Plan", "Plan")
                        .WithMany("TrainingSessions")
                        .HasForeignKey("PlanId");

                    b.Navigation("AccessPolicy");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Trainova.Domain.UserAuth.UserRoles.UserRole", b =>
                {
                    b.HasOne("Trainova.Domain.UserAuth.Roles.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trainova.Domain.UserAuth.Roles.Role", null)
                        .WithMany("Roles")
                        .HasForeignKey("RoleId1");

                    b.HasOne("Trainova.Domain.UserAuth.Users.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Trainova.Domain.UserAuth.UserTokens.UserToken", b =>
                {
                    b.HasOne("Trainova.Domain.UserAuth.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Trainova.Domain.UserAuth.Users.User", b =>
                {
                    b.HasOne("Trainova.Domain.Profiles.Players.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");

                    b.HasOne("Trainova.Domain.SeasonsAnalyses.Teams.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId");

                    b.HasOne("Trainova.Domain.Profiles.TeamsStaff.TeamStaff", "TeamStaff")
                        .WithMany()
                        .HasForeignKey("TeamStaffId");

                    b.Navigation("Player");

                    b.Navigation("Team");

                    b.Navigation("TeamStaff");
                });

            modelBuilder.Entity("Trainova.Domain.MedicalStatus.Injuries.Injury", b =>
                {
                    b.Navigation("PlayerInjuries");
                });

            modelBuilder.Entity("Trainova.Domain.Profiles.Players.Player", b =>
                {
                    b.Navigation("PlayerInjuries");
                });

            modelBuilder.Entity("Trainova.Domain.TrainingSessionsAccessibility.AccessPolicies.AccessPolicy", b =>
                {
                    b.Navigation("PolicyUsers");
                });

            modelBuilder.Entity("Trainova.Domain.TrainingSessionsAccessibility.Plans.Plan", b =>
                {
                    b.Navigation("TrainingSessions");
                });

            modelBuilder.Entity("Trainova.Domain.TrainingSessionsAccessibility.TrainingSessions.TrainingSession", b =>
                {
                    b.Navigation("Match");

                    b.Navigation("UserAccessPolicies");
                });

            modelBuilder.Entity("Trainova.Domain.UserAuth.Roles.Role", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Trainova.Domain.UserAuth.Users.User", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
