// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trainova.Infrastructure.DataAccess;

#nullable disable

namespace Trainova.Infrastructure.DataAccess.Migrations
{
    [DbContext(typeof(TrainovaWriteDbContext))]
    [Migration("20260608213434_UpdateScoutingCandidate")]
    partial class UpdateScoutingCandidate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Trainova.Domain.Common.AuditLogs.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("From")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRecovered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RecoveredAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("RecoveredByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("EntityId");

                    b.HasIndex("EntityName");

                    b.HasIndex("IsRecovered");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.Common.Outbox.DomainEventOutbox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.PrimitiveCollection<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("HandledAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsHandled")
                        .HasColumnType("bit");

                    b.Property<string>("Notification")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DomainEventOutboxes");
                });

            modelBuilder.Entity("Trainova.Domain.Common.Outbox.EmailOutbox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSent")
                        .HasColumnType("bit");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("EmailOutboxes", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.FitnessStatus.FitnessExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FitnessExercises");
                });

            modelBuilder.Entity("Trainova.Domain.FitnessStatus.FitnessSessionExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ActiveTimeSec")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Intensity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoadDetails")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Reps")
                        .HasColumnType("int");

                    b.Property<int?>("RestTimeSec")
                        .HasColumnType("int");

                    b.Property<int?>("Rounds")
                        .HasColumnType("int");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Sets")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("SessionId");

                    b.ToTable("FitnessSessionExercises", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.FitnessStatus.PhysicalCapacityTest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CalculatedCapacity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CreationType")
                        .HasColumnType("int");

                    b.Property<decimal?>("OverriddenCapacity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ProgressFromLastTest")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("CapacityTests", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.FitnessStatus.SessionMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("int");

                    b.Property<decimal>("FootageLoadToCapacityRatio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FootageStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LoadRatioFromLastSession")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OverriddenLoad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PlayerCalculatedLoad")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("SprintsCount")
                        .HasColumnType("int");

                    b.Property<Guid>("UserAccessPolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserAccessPolicyId")
                        .IsUnique();

                    b.ToTable("SessionMovements");
                });

            modelBuilder.Entity("Trainova.Domain.MatchsManagement.ComputedFeatures.ComputedFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("ActionsPer90")
                        .HasColumnType("float");

                    b.Property<double>("ActivityDrop2ndHalf")
                        .HasColumnType("float");

                    b.Property<double>("AvgPositionX")
                        .HasColumnType("float");

                    b.Property<double>("AvgPositionY")
                        .HasColumnType("float");

                    b.Property<double>("AvgSpeed")
                        .HasColumnType("float");

                    b.Property<double>("BallRetentionRate")
                        .HasColumnType("float");

                    b.Property<double>("CarrySuccessRate")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("DefensiveValue")
                        .HasColumnType("float");

                    b.Property<double>("DistanceCovered")
                        .HasColumnType("float");

                    b.Property<double>("DribbleSuccessRate")
                        .HasColumnType("float");

                    b.Property<int>("FoulsCommitted")
                        .HasColumnType("int");

                    b.Property<int>("FoulsWon")
                        .HasColumnType("int");

                    b.Property<int>("HighIntensityActions")
                        .HasColumnType("int");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("OffensiveValue")
                        .HasColumnType("float");

                    b.Property<double>("PassAccuracy")
                        .HasColumnType("float");

                    b.Property<int>("PassesUnderPressure")
                        .HasColumnType("int");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("PositionDeviation")
                        .HasColumnType("float");

                    b.Property<double>("Ppda")
                        .HasColumnType("float");

                    b.Property<int>("PressureRegains")
                        .HasColumnType("int");

                    b.Property<int>("ProgressiveCarries")
                        .HasColumnType("int");

                    b.Property<int>("ProgressivePasses")
                        .HasColumnType("int");

                    b.Property<int>("RedCards")
                        .HasColumnType("int");

                    b.Property<double>("ShotAccuracy")
                        .HasColumnType("float");

                    b.Property<int>("ShotsOnTarget")
                        .HasColumnType("int");

                    b.Property<int>("SprintCount")
                        .HasColumnType("int");

                    b.Property<int>("TotalPasses")
                        .HasColumnType("int");

                    b.Property<int>("TotalPressures")
                        .HasColumnType("int");

                    b.Property<int>("TotalShots")
                        .HasColumnType("int");

                    b.Property<double>("TotalXg")
                        .HasColumnType("float");

                    b.Property<double>("VaepRating")
                        .HasColumnType("float");

                    b.Property<double>("XgPerShot")
                        .HasColumnType("float");

                    b.Property<int>("YellowCards")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId");

                    b.ToTable("ComputedFeatures", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.MatchsManagement.Events.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BodyPart")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<double?>("CarryEndX")
                        .HasColumnType("float");

                    b.Property<double?>("CarryEndY")
                        .HasColumnType("float");

                    b.Property<bool?>("CounterPress")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DribbleOutcome")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int?>("EventIndex")
                        .HasColumnType("int");

                    b.Property<string>("EventType")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<bool?>("IsProgressivePass")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("LocationX")
                        .HasColumnType("float");

                    b.Property<double?>("LocationY")
                        .HasColumnType("float");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Minute")
                        .HasColumnType("tinyint");

                    b.Property<double?>("PassAngle")
                        .HasColumnType("float");

                    b.Property<double?>("PassEndX")
                        .HasColumnType("float");

                    b.Property<double?>("PassEndY")
                        .HasColumnType("float");

                    b.Property<double?>("PassLength")
                        .HasColumnType("float");

                    b.Property<string>("PassOutcome")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("PredictedXg")
                        .HasColumnType("float");

                    b.Property<double?>("PressureDuration")
                        .HasColumnType("float");

                    b.Property<byte>("Second")
                        .HasColumnType("tinyint");

                    b.Property<bool?>("ShotAfterSetPiece")
                        .HasColumnType("bit");

                    b.Property<double?>("ShotEndX")
                        .HasColumnType("float");

                    b.Property<double?>("ShotEndY")
                        .HasColumnType("float");

                    b.Property<string>("ShotOutcome")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("ShotTechnique")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<double?>("ShotXg")
                        .HasColumnType("float");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("Timestamp")
                        .HasColumnType("time");

                    b.Property<bool?>("UnderPressure")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.MatchsManagement.Lineups.Lineup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsStarter")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MinutesPlayed")
                        .HasColumnType("int");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StartingPosition")
                        .HasColumnType("int");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("StartingPosition");

                    b.HasIndex("TeamId");

                    b.ToTable("Lineups", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.MatchsManagement.Matches.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("AwayScore")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("AwayTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("HomeScore")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("MatchDate")
                        .HasColumnType("date");

                    b.Property<int>("MatchWeek")
                        .HasColumnType("int");

                    b.Property<string>("Referee")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Stadium")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("MatchDate");

                    b.ToTable("Matches", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.MatchsManagement.Videos.MatchVideo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ObjectStoregeProviderId")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("RelatedMatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.HasKey("Id");

                    b.HasIndex("RelatedMatchId");

                    b.ToTable("MatchVideos", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.MedicalStatus.Injury", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AverageRecoveryTimeInDayes")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1200)
                        .HasColumnType("nvarchar(1200)");

                    b.Property<string>("InjuryType")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("InjuryType");

                    b.ToTable("Injuries", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.MedicalStatus.PlayerInjury", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BodyPart")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Cause")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ExpectedReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HappendAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InjuryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsNew")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(1200)
                        .HasColumnType("nvarchar(1200)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SevertiyGrade")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("InjuryId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("Status");

                    b.ToTable("PlayerInjuries", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.Profiles.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentMainPosition")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfEnrolment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MedicalStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("OtherAvailablePositions")
                        .HasColumnType("int");

                    b.Property<decimal>("PerformanceLevel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PlayerNumber")
                        .HasColumnType("int");

                    b.Property<string>("TShirtName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Players", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.Profiles.TeamStaff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContractFilesLink")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InsuranceFilesLink")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("TeamStaffs", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.Scouting.CandidateMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Assists")
                        .HasColumnType("int");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Goals")
                        .HasColumnType("int");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MatchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<string>("ScoutNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ScoutingCandidateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ScoutingCandidateId");

                    b.ToTable("CandidateMatch");
                });

            modelBuilder.Entity("Trainova.Domain.Scouting.ScoutingCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrentTeamName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("CurrentTeamName");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MatchesWatchedCount")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1200)
                        .HasColumnType("nvarchar(1200)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<float>("ScoutRating")
                        .HasColumnType("real");

                    b.Property<int?>("ShortlistRank")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.HasIndex("CurrentTeamName");

                    b.ToTable("ScoutingCandidates", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.Scouting.ScoutingCandidateNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ScoutingCandidateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ScoutingCandidateId");

                    b.ToTable("ScoutingCandidateNote");
                });

            modelBuilder.Entity("Trainova.Domain.SeasonsAnalyses.Competition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompetitionName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CountryName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SeasonName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("Competitions", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.SeasonsAnalyses.ModelScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("BehavioralScore")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("MovementScore")
                        .HasColumnType("float");

                    b.Property<double>("OverallScore")
                        .HasColumnType("float");

                    b.Property<double>("PassingScore")
                        .HasColumnType("float");

                    b.Property<double>("PercentileInLeague")
                        .HasColumnType("float");

                    b.Property<double>("PercentileInPosition")
                        .HasColumnType("float");

                    b.Property<double>("PercentileInTeam")
                        .HasColumnType("float");

                    b.Property<string>("PerformanceTrend")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<double>("PhysicalScore")
                        .HasColumnType("float");

                    b.Property<string>("PlayerCluster")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("PositionFitScore")
                        .HasColumnType("float");

                    b.Property<double>("PositioningScore")
                        .HasColumnType("float");

                    b.Property<double>("PressingScore")
                        .HasColumnType("float");

                    b.Property<double>("ShootingScore")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId");

                    b.ToTable("ModelScores", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.SeasonsAnalyses.PositionBenchmark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("AvgDistanceCovered")
                        .HasColumnType("float");

                    b.Property<double?>("AvgPassAccuracy")
                        .HasColumnType("float");

                    b.Property<double?>("AvgPressures")
                        .HasColumnType("float");

                    b.Property<double?>("AvgProgressivePasses")
                        .HasColumnType("float");

                    b.Property<double?>("AvgVaep")
                        .HasColumnType("float");

                    b.Property<double?>("AvgXg")
                        .HasColumnType("float");

                    b.Property<int>("CompetitionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PositionGroup")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.Property<double?>("WeightBehavioral")
                        .HasColumnType("float");

                    b.Property<double?>("WeightMovement")
                        .HasColumnType("float");

                    b.Property<double?>("WeightPassing")
                        .HasColumnType("float");

                    b.Property<double?>("WeightPhysical")
                        .HasColumnType("float");

                    b.Property<double?>("WeightPositioning")
                        .HasColumnType("float");

                    b.Property<double?>("WeightPressing")
                        .HasColumnType("float");

                    b.Property<double?>("WeightShooting")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("SeasonId");

                    b.ToTable("PositionBenchmarks", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.SeasonsAnalyses.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TeamName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Teams", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.TrainingSessionsAccessibility.AccessPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AccessPolicies", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.TrainingSessionsAccessibility.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccessPolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlanGoul")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PlanType")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccessPolicyId");

                    b.ToTable("Plans", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.TrainingSessionsAccessibility.TrainingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccessPolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("HappenedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Place")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<Guid?>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SessionState")
                        .HasColumnType("int");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrainingSessionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AccessPolicyId");

                    b.HasIndex("PlanId");

                    b.ToTable("TrainingSessions", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.TrainingSessionsAccessibility.UserAccessPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccessPoliciesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttendanceState")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DoneScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccessPoliciesId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAccessPolicies", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.UserAuth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsTFAEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShowName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("TFAEnabledAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("_passwordHash")
                        .IsRequired()
                        .HasMaxLength(2400)
                        .HasColumnType("nvarchar(2400)")
                        .HasColumnName("PasswordHash");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Role");

                    b.HasIndex("TeamId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Trainova.Domain.UserAuth.UserToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<int?>("RevokeCause")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.FitnessStatus.FitnessSessionExercise", b =>
                {
                    b.HasOne("Trainova.Domain.FitnessStatus.FitnessExercise", "Exercise")
                        .WithMany("SessionExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trainova.Domain.TrainingSessionsAccessibility.TrainingSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Trainova.Domain.FitnessStatus.PhysicalCapacityTest", b =>
                {
                    b.OwnsOne("Trainova.Domain.FitnessStatus.AerobicCapacityTest", "AerobicCapacityTest", b1 =>
                        {
                            b1.Property<Guid>("PhysicalCapacityTestId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("MaximumOxygenConsumption")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("MaximumOxygenConsumption");

                            b1.Property<int>("YoYoIntermittentRecoveryLevel1Distance")
                                .HasColumnType("int")
                                .HasColumnName("YoYoIntermittentRecoveryLevel1Distance");

                            b1.Property<int>("YoYoIntermittentRecoveryLevel2Distance")
                                .HasColumnType("int")
                                .HasColumnName("YoYoIntermittentRecoveryLevel2Distance");

                            b1.HasKey("PhysicalCapacityTestId");

                            b1.ToTable("CapacityTests");

                            b1.WithOwner()
                                .HasForeignKey("PhysicalCapacityTestId");
                        });

                    b.OwnsOne("Trainova.Domain.FitnessStatus.ExplosivePowerTest", "ExplosivePowerTest", b1 =>
                        {
                            b1.Property<Guid>("PhysicalCapacityTestId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("CountermovementJumpHeight")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("CountermovementJumpHeight");

                            b1.Property<decimal>("ReactiveStrengthIndex")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("ReactiveStrengthIndex");

                            b1.HasKey("PhysicalCapacityTestId");

                            b1.ToTable("CapacityTests");

                            b1.WithOwner()
                                .HasForeignKey("PhysicalCapacityTestId");
                        });

                    b.OwnsOne("Trainova.Domain.FitnessStatus.SprintTest", "SprintTest", b1 =>
                        {
                            b1.Property<Guid>("PhysicalCapacityTestId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Time10Meters")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("Time10Meters");

                            b1.Property<decimal>("Time30Meters")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("Time30Meters");

                            b1.HasKey("PhysicalCapacityTestId");

                            b1.ToTable("CapacityTests");

                            b1.WithOwner()
                                .HasForeignKey("PhysicalCapacityTestId");
                        });

                    b.Navigation("AerobicCapacityTest")
                        .IsRequired();

                    b.Navigation("ExplosivePowerTest")
                        .IsRequired();

                    b.Navigation("SprintTest")
                        .IsRequired();
                });

            modelBuilder.Entity("Trainova.Domain.FitnessStatus.SessionMovement", b =>
                {
                    b.HasOne("Trainova.Domain.TrainingSessionsAccessibility.UserAccessPolicy", "UserAccessPolicy")
                        .WithOne("SessionMovement")
                        .HasForeignKey("Trainova.Domain.FitnessStatus.SessionMovement", "UserAccessPolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Trainova.Domain.FitnessStatus.Distance", "Distance", b1 =>
                        {
                            b1.Property<Guid>("SessionMovementId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("HighSpeedRunDistance")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("HighSpeedRunDistance");

                            b1.Property<decimal>("RunDistance")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("RunDistance");

                            b1.Property<decimal>("TotalDistance")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("TotalDistance");

                            b1.Property<decimal>("WalkDistance")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("WalkDistance");

                            b1.HasKey("SessionMovementId");

                            b1.ToTable("SessionMovements");

                            b1.WithOwner()
                                .HasForeignKey("SessionMovementId");
                        });

                    b.OwnsOne("Trainova.Domain.FitnessStatus.Speed", "Speed", b1 =>
                        {
                            b1.Property<Guid>("SessionMovementId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("AverageSpeed")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("AverageSpeed");

                            b1.Property<decimal>("MaxSpeed")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("MaxSpeed");

                            b1.Property<decimal>("PeakAcceleration")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("PeakAcceleration");

                            b1.HasKey("SessionMovementId");

                            b1.ToTable("SessionMovements");

                            b1.WithOwner()
                                .HasForeignKey("SessionMovementId");
                        });

                    b.Navigation("Distance");

                    b.Navigation("Speed");

                    b.Navigation("UserAccessPolicy");
                });

            modelBuilder.Entity("Trainova.Domain.MatchsManagement.Matches.Match", b =>
                {
                    b.HasOne("Trainova.Domain.TrainingSessionsAccessibility.TrainingSession", "TrainingSession")
                        .WithOne("Match")
                        .HasForeignKey("Trainova.Domain.MatchsManagement.Matches.Match", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingSession");
                });

            modelBuilder.Entity("Trainova.Domain.MedicalStatus.PlayerInjury", b =>
                {
                    b.HasOne("Trainova.Domain.MedicalStatus.Injury", "Injury")
                        .WithMany("PlayerInjuries")
                        .HasForeignKey("InjuryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trainova.Domain.Profiles.Player", "Player")
                        .WithMany("PlayerInjuries")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Trainova.Domain.MedicalStatus.RecoveryPlanPhase", "Phases", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Activities")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<Guid?>("CreatedBy")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Description")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("From")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime?>("LastUpdate")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Order")
                                .HasColumnType("int");

                            b1.Property<Guid>("PlayerInjuryId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("To")
                                .HasColumnType("datetime2");

                            b1.HasKey("Id");

                            b1.HasIndex("PlayerInjuryId", "Order");

                            b1.ToTable("RecoveryPlanPhases", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PlayerInjuryId");
                        });

                    b.Navigation("Injury");

                    b.Navigation("Phases");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Trainova.Domain.Profiles.Player", b =>
                {
                    b.HasOne("Trainova.Domain.UserAuth.User", "User")
                        .WithOne("Player")
                        .HasForeignKey("Trainova.Domain.Profiles.Player", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Trainova.Domain.Profiles.TeamStaff", b =>
                {
                    b.HasOne("Trainova.Domain.UserAuth.User", "User")
                        .WithOne("TeamStaff")
                        .HasForeignKey("Trainova.Domain.Profiles.TeamStaff", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Trainova.Domain.Scouting.CandidateMatch", b =>
                {
                    b.HasOne("Trainova.Domain.Scouting.ScoutingCandidate", null)
                        .WithMany("MatchesList")
                        .HasForeignKey("ScoutingCandidateId");
                });

            modelBuilder.Entity("Trainova.Domain.Scouting.ScoutingCandidate", b =>
                {
                    b.OwnsOne("Trainova.Domain.Scouting.ValueObjects.ContractInfo", "ContractInfo", b1 =>
                        {
                            b1.Property<Guid>("ScoutingCandidateId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Agent")
                                .HasMaxLength(400)
                                .HasColumnType("nvarchar(400)")
                                .HasColumnName("Agent");

                            b1.Property<DateTime?>("ContractEnd")
                                .HasColumnType("datetime2")
                                .HasColumnName("ContractEnd");

                            b1.Property<decimal?>("MarketValue")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("MarketValue");

                            b1.Property<string>("Nationality")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Nationality");

                            b1.HasKey("ScoutingCandidateId");

                            b1.ToTable("ScoutingCandidates");

                            b1.WithOwner()
                                .HasForeignKey("ScoutingCandidateId");
                        });

                    b.OwnsOne("Trainova.Domain.Scouting.ValueObjects.PersonalDetails", "PersonalDetails", b1 =>
                        {
                            b1.Property<Guid>("ScoutingCandidateId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("DateOfBirth")
                                .HasColumnType("datetime2")
                                .HasColumnName("DateOfBirth");

                            b1.Property<int?>("Height")
                                .HasColumnType("int")
                                .HasColumnName("Height");

                            b1.Property<string>("PreferredFoot")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("PreferredFoot");

                            b1.Property<int?>("Weight")
                                .HasColumnType("int")
                                .HasColumnName("Weight");

                            b1.HasKey("ScoutingCandidateId");

                            b1.ToTable("ScoutingCandidates");

                            b1.WithOwner()
                                .HasForeignKey("ScoutingCandidateId");
                        });

                    b.OwnsOne("Trainova.Domain.Scouting.ValueObjects.SkillAssessment", "SkillAssessment", b1 =>
                        {
                            b1.Property<Guid>("ScoutingCandidateId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Defending")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(0)
                                .HasColumnName("Defending");

                            b1.Property<int>("Dribbling")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(0)
                                .HasColumnName("Dribbling");

                            b1.Property<int>("Pace")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(0)
                                .HasColumnName("Pace");

                            b1.Property<int>("Passing")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(0)
                                .HasColumnName("Passing");

                            b1.Property<int>("Physicality")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(0)
                                .HasColumnName("Physicality");

                            b1.Property<int>("Positioning")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(0)
                                .HasColumnName("Positioning");

                            b1.Property<int>("Shooting")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(0)
                                .HasColumnName("Shooting");

                            b1.Property<int>("Vision")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(0)
                                .HasColumnName("Vision");

                            b1.HasKey("ScoutingCandidateId");

                            b1.ToTable("ScoutingCandidates");

                            b1.WithOwner()
                                .HasForeignKey("ScoutingCandidateId");
                        });

                    b.Navigation("ContractInfo")
                        .IsRequired();

                    b.Navigation("PersonalDetails")
                        .IsRequired();

                    b.Navigation("SkillAssessment")
                        .IsRequired();
                });

            modelBuilder.Entity("Trainova.Domain.Scouting.ScoutingCandidateNote", b =>
                {
                    b.HasOne("Trainova.Domain.Scouting.ScoutingCandidate", null)
                        .WithMany("NotesList")
                        .HasForeignKey("ScoutingCandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Trainova.Domain.TrainingSessionsAccessibility.Plan", b =>
                {
                    b.HasOne("Trainova.Domain.TrainingSessionsAccessibility.AccessPolicy", "AccessPolicy")
                        .WithMany()
                        .HasForeignKey("AccessPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessPolicy");
                });

            modelBuilder.Entity("Trainova.Domain.TrainingSessionsAccessibility.TrainingSession", b =>
                {
                    b.HasOne("Trainova.Domain.TrainingSessionsAccessibility.AccessPolicy", "AccessPolicy")
                        .WithMany()
                        .HasForeignKey("AccessPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trainova.Domain.TrainingSessionsAccessibility.Plan", "Plan")
                        .WithMany("TrainingSessions")
                        .HasForeignKey("PlanId");

                    b.Navigation("AccessPolicy");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Trainova.Domain.TrainingSessionsAccessibility.UserAccessPolicy", b =>
                {
                    b.HasOne("Trainova.Domain.TrainingSessionsAccessibility.AccessPolicy", "AccessPolicy")
                        .WithMany("PolicyUsers")
                        .HasForeignKey("AccessPoliciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trainova.Domain.UserAuth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessPolicy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Trainova.Domain.UserAuth.User", b =>
                {
                    b.HasOne("Trainova.Domain.SeasonsAnalyses.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Trainova.Domain.UserAuth.UserToken", b =>
                {
                    b.HasOne("Trainova.Domain.UserAuth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Trainova.Domain.FitnessStatus.FitnessExercise", b =>
                {
                    b.Navigation("SessionExercises");
                });

            modelBuilder.Entity("Trainova.Domain.MedicalStatus.Injury", b =>
                {
                    b.Navigation("PlayerInjuries");
                });

            modelBuilder.Entity("Trainova.Domain.Profiles.Player", b =>
                {
                    b.Navigation("PlayerInjuries");
                });

            modelBuilder.Entity("Trainova.Domain.Scouting.ScoutingCandidate", b =>
                {
                    b.Navigation("MatchesList");

                    b.Navigation("NotesList");
                });

            modelBuilder.Entity("Trainova.Domain.TrainingSessionsAccessibility.AccessPolicy", b =>
                {
                    b.Navigation("PolicyUsers");
                });

            modelBuilder.Entity("Trainova.Domain.TrainingSessionsAccessibility.Plan", b =>
                {
                    b.Navigation("TrainingSessions");
                });

            modelBuilder.Entity("Trainova.Domain.TrainingSessionsAccessibility.TrainingSession", b =>
                {
                    b.Navigation("Match");
                });

            modelBuilder.Entity("Trainova.Domain.TrainingSessionsAccessibility.UserAccessPolicy", b =>
                {
                    b.Navigation("SessionMovement");
                });

            modelBuilder.Entity("Trainova.Domain.UserAuth.User", b =>
                {
                    b.Navigation("Player");

                    b.Navigation("TeamStaff");
                });
#pragma warning restore 612, 618
        }
    }
}
