// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trainova.Infrastructure.DataAccess;

#nullable disable

namespace Trainova.Infrastructure.DataAccess.Migrations
{
    [DbContext(typeof(TrainovaWriteDbContext))]
    partial class TrainovaWriteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Trainova.Domain.Common.AuditLogs.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("From")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRecovered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RecoveredAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("RecoveredByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.Common.Outbox.EmailOutbox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSent")
                        .HasColumnType("bit");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("EmailOutboxes", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.MatchsManagement.ComputedFeatures.ComputedFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("ActionsPer90")
                        .HasColumnType("float");

                    b.Property<double>("ActivityDrop2ndHalf")
                        .HasColumnType("float");

                    b.Property<double>("AvgPositionX")
                        .HasColumnType("float");

                    b.Property<double>("AvgPositionY")
                        .HasColumnType("float");

                    b.Property<double>("AvgSpeed")
                        .HasColumnType("float");

                    b.Property<double>("BallRetentionRate")
                        .HasColumnType("float");

                    b.Property<double>("CarrySuccessRate")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("DefensiveValue")
                        .HasColumnType("float");

                    b.Property<double>("DistanceCovered")
                        .HasColumnType("float");

                    b.Property<double>("DribbleSuccessRate")
                        .HasColumnType("float");

                    b.Property<int>("FoulsCommitted")
                        .HasColumnType("int");

                    b.Property<int>("FoulsWon")
                        .HasColumnType("int");

                    b.Property<int>("HighIntensityActions")
                        .HasColumnType("int");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("OffensiveValue")
                        .HasColumnType("float");

                    b.Property<double>("PassAccuracy")
                        .HasColumnType("float");

                    b.Property<int>("PassesUnderPressure")
                        .HasColumnType("int");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("PositionDeviation")
                        .HasColumnType("float");

                    b.Property<double>("Ppda")
                        .HasColumnType("float");

                    b.Property<int>("PressureRegains")
                        .HasColumnType("int");

                    b.Property<int>("ProgressiveCarries")
                        .HasColumnType("int");

                    b.Property<int>("ProgressivePasses")
                        .HasColumnType("int");

                    b.Property<int>("RedCards")
                        .HasColumnType("int");

                    b.Property<double>("ShotAccuracy")
                        .HasColumnType("float");

                    b.Property<int>("ShotsOnTarget")
                        .HasColumnType("int");

                    b.Property<int>("SprintCount")
                        .HasColumnType("int");

                    b.Property<int>("TotalPasses")
                        .HasColumnType("int");

                    b.Property<int>("TotalPressures")
                        .HasColumnType("int");

                    b.Property<int>("TotalShots")
                        .HasColumnType("int");

                    b.Property<double>("TotalXg")
                        .HasColumnType("float");

                    b.Property<double>("VaepRating")
                        .HasColumnType("float");

                    b.Property<double>("XgPerShot")
                        .HasColumnType("float");

                    b.Property<int>("YellowCards")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId");

                    b.ToTable("ComputedFeature");
                });

            modelBuilder.Entity("Trainova.Domain.MatchsManagement.Events.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BodyPart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("CarryEndX")
                        .HasColumnType("float");

                    b.Property<double?>("CarryEndY")
                        .HasColumnType("float");

                    b.Property<bool?>("CounterPress")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DribbleOutcome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EventIndex")
                        .HasColumnType("int");

                    b.Property<string>("EventType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsProgressivePass")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("LocationX")
                        .HasColumnType("float");

                    b.Property<double?>("LocationY")
                        .HasColumnType("float");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Minute")
                        .HasColumnType("tinyint");

                    b.Property<double?>("PassAngle")
                        .HasColumnType("float");

                    b.Property<double?>("PassEndX")
                        .HasColumnType("float");

                    b.Property<double?>("PassEndY")
                        .HasColumnType("float");

                    b.Property<double?>("PassLength")
                        .HasColumnType("float");

                    b.Property<string>("PassOutcome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("PredictedXg")
                        .HasColumnType("float");

                    b.Property<double?>("PressureDuration")
                        .HasColumnType("float");

                    b.Property<byte>("Second")
                        .HasColumnType("tinyint");

                    b.Property<bool?>("ShotAfterSetPiece")
                        .HasColumnType("bit");

                    b.Property<double?>("ShotEndX")
                        .HasColumnType("float");

                    b.Property<double?>("ShotEndY")
                        .HasColumnType("float");

                    b.Property<string>("ShotOutcome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShotTechnique")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("ShotXg")
                        .HasColumnType("float");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("Timestamp")
                        .HasColumnType("time");

                    b.Property<bool?>("UnderPressure")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("Trainova.Domain.MatchsManagement.Lineups.Lineup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsStarter")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MinutesPlayed")
                        .HasColumnType("int");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("StartingPosition")
                        .HasColumnType("int");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("Lineup");
                });

            modelBuilder.Entity("Trainova.Domain.MatchsManagement.Matches.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("AwayScore")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("AwayTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("HomeScore")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("MatchDate")
                        .HasColumnType("date");

                    b.Property<int>("MatchWeek")
                        .HasColumnType("int");

                    b.Property<string>("Referee")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stadium")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Match");
                });

            modelBuilder.Entity("Trainova.Domain.MedicalStatus.Injuries.Injury", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan?>("AverageRecoveryTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1200)
                        .HasColumnType("nvarchar(1200)");

                    b.Property<string>("InjuryType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Injuries", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.MedicalStatus.PlayerInjuries.PlayerInjury", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Cause")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ExpectedReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HappendAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InjuryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InjuryId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerInjuries");
                });

            modelBuilder.Entity("Trainova.Domain.Profiles.Players.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentMainPosition")
                        .HasColumnType("int");

                    b.Property<Guid>("CurrentTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfEnrolment")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MedecalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OtherAvailablePositions")
                        .HasColumnType("int");

                    b.Property<decimal>("PerformanceLevel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PlayerNumber")
                        .HasColumnType("int");

                    b.Property<string>("TShirtName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CurrentTeamId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Players", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.Profiles.TeamsStaff.TeamStaff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContractFilesLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InsuranceFilesLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("Coaches");
                });

            modelBuilder.Entity("Trainova.Domain.SeasonsAnalyses.ModelScores.ModelScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("BehavioralScore")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("MovementScore")
                        .HasColumnType("float");

                    b.Property<double>("OverallScore")
                        .HasColumnType("float");

                    b.Property<double>("PassingScore")
                        .HasColumnType("float");

                    b.Property<double>("PercentileInLeague")
                        .HasColumnType("float");

                    b.Property<double>("PercentileInPosition")
                        .HasColumnType("float");

                    b.Property<double>("PercentileInTeam")
                        .HasColumnType("float");

                    b.Property<string>("PerformanceTrend")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PhysicalScore")
                        .HasColumnType("float");

                    b.Property<string>("PlayerCluster")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("PositionFitScore")
                        .HasColumnType("float");

                    b.Property<double>("PositioningScore")
                        .HasColumnType("float");

                    b.Property<double>("PressingScore")
                        .HasColumnType("float");

                    b.Property<double>("ShootingScore")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId");

                    b.ToTable("ModelScore");
                });

            modelBuilder.Entity("Trainova.Domain.SeasonsAnalyses.Teams.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TeamName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("Trainova.Domain.TrainingSessionsAccessibility.AccessPolicies.AccessPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PolicyName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AccessPolicy");
                });

            modelBuilder.Entity("Trainova.Domain.TrainingSessionsAccessibility.AccessPolicies.UserAccessPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccessPoliciesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccessPolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttendanceState")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DoneScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TrainingSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccessPolicyId");

                    b.HasIndex("TrainingSessionId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAccessPolicy");
                });

            modelBuilder.Entity("Trainova.Domain.TrainingSessionsAccessibility.Plans.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccessPolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlanGoul")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccessPolicyId");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("Trainova.Domain.TrainingSessionsAccessibility.TrainingSessions.TrainingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("HappenedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Place")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SessionState")
                        .HasColumnType("int");

                    b.Property<string>("TrainingSessionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("TrainingSessions");
                });

            modelBuilder.Entity("Trainova.Domain.UserAuth.Roles.Role", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Trainova.Domain.UserAuth.UserRoles.UserRole", b =>
                {
                    b.Property<byte>("RoleId")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("RoleId1")
                        .HasColumnType("tinyint");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("RoleId1");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.UserAuth.UserTokens.UserToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<int?>("RevokeCause")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("Trainova.Domain.UserAuth.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShowName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Trainova.Domain.MatchsManagement.ComputedFeatures.ComputedFeature", b =>
                {
                    b.HasOne("Trainova.Domain.MatchsManagement.Matches.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trainova.Domain.Profiles.Players.Player", "Player")
                        .WithMany("ComputedFeatures")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Trainova.Domain.MatchsManagement.Events.Event", b =>
                {
                    b.HasOne("Trainova.Domain.MatchsManagement.Matches.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trainova.Domain.Profiles.Players.Player", "Player")
                        .WithMany("Events")
                        .HasForeignKey("PlayerId");

                    b.HasOne("Trainova.Domain.SeasonsAnalyses.Teams.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId");

                    b.Navigation("Match");

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Trainova.Domain.MatchsManagement.Lineups.Lineup", b =>
                {
                    b.HasOne("Trainova.Domain.MatchsManagement.Matches.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trainova.Domain.Profiles.Players.Player", "Player")
                        .WithMany("Lineups")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trainova.Domain.SeasonsAnalyses.Teams.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Trainova.Domain.MedicalStatus.PlayerInjuries.PlayerInjury", b =>
                {
                    b.HasOne("Trainova.Domain.MedicalStatus.Injuries.Injury", "Injury")
                        .WithMany("PlayerInjuries")
                        .HasForeignKey("InjuryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trainova.Domain.Profiles.Players.Player", "Player")
                        .WithMany("PlayerInjuries")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Injury");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Trainova.Domain.Profiles.Players.Player", b =>
                {
                    b.HasOne("Trainova.Domain.SeasonsAnalyses.Teams.Team", "CurrentTeam")
                        .WithMany()
                        .HasForeignKey("CurrentTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trainova.Domain.UserAuth.Users.User", "User")
                        .WithOne()
                        .HasForeignKey("Trainova.Domain.Profiles.Players.Player", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentTeam");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Trainova.Domain.Profiles.TeamsStaff.TeamStaff", b =>
                {
                    b.HasOne("Trainova.Domain.SeasonsAnalyses.Teams.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trainova.Domain.UserAuth.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Trainova.Domain.SeasonsAnalyses.ModelScores.ModelScore", b =>
                {
                    b.HasOne("Trainova.Domain.MatchsManagement.Matches.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trainova.Domain.Profiles.Players.Player", "Player")
                        .WithMany("ModelScores")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Trainova.Domain.TrainingSessionsAccessibility.AccessPolicies.UserAccessPolicy", b =>
                {
                    b.HasOne("Trainova.Domain.TrainingSessionsAccessibility.AccessPolicies.AccessPolicy", "AccessPolicy")
                        .WithMany("PolicyUsers")
                        .HasForeignKey("AccessPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trainova.Domain.TrainingSessionsAccessibility.TrainingSessions.TrainingSession", null)
                        .WithMany("UserAccessPolicies")
                        .HasForeignKey("TrainingSessionId");

                    b.HasOne("Trainova.Domain.UserAuth.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessPolicy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Trainova.Domain.TrainingSessionsAccessibility.Plans.Plan", b =>
                {
                    b.HasOne("Trainova.Domain.TrainingSessionsAccessibility.AccessPolicies.AccessPolicy", "AccessPolicy")
                        .WithMany()
                        .HasForeignKey("AccessPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessPolicy");
                });

            modelBuilder.Entity("Trainova.Domain.TrainingSessionsAccessibility.TrainingSessions.TrainingSession", b =>
                {
                    b.HasOne("Trainova.Domain.TrainingSessionsAccessibility.Plans.Plan", "Plan")
                        .WithMany("TrainingSessions")
                        .HasForeignKey("PlanId");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Trainova.Domain.UserAuth.UserRoles.UserRole", b =>
                {
                    b.HasOne("Trainova.Domain.UserAuth.Roles.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trainova.Domain.UserAuth.Roles.Role", null)
                        .WithMany("Roles")
                        .HasForeignKey("RoleId1");

                    b.HasOne("Trainova.Domain.UserAuth.Users.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Trainova.Domain.UserAuth.UserTokens.UserToken", b =>
                {
                    b.HasOne("Trainova.Domain.UserAuth.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Trainova.Domain.MedicalStatus.Injuries.Injury", b =>
                {
                    b.Navigation("PlayerInjuries");
                });

            modelBuilder.Entity("Trainova.Domain.Profiles.Players.Player", b =>
                {
                    b.Navigation("ComputedFeatures");

                    b.Navigation("Events");

                    b.Navigation("Lineups");

                    b.Navigation("ModelScores");

                    b.Navigation("PlayerInjuries");
                });

            modelBuilder.Entity("Trainova.Domain.TrainingSessionsAccessibility.AccessPolicies.AccessPolicy", b =>
                {
                    b.Navigation("PolicyUsers");
                });

            modelBuilder.Entity("Trainova.Domain.TrainingSessionsAccessibility.Plans.Plan", b =>
                {
                    b.Navigation("TrainingSessions");
                });

            modelBuilder.Entity("Trainova.Domain.TrainingSessionsAccessibility.TrainingSessions.TrainingSession", b =>
                {
                    b.Navigation("UserAccessPolicies");
                });

            modelBuilder.Entity("Trainova.Domain.UserAuth.Roles.Role", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Trainova.Domain.UserAuth.Users.User", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
