import sys
from pathlib import Path
from unittest.mock import patch

import numpy as np
import pandas as pd
import pytest
from fastapi.testclient import TestClient

root = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(root))


# ── Sample Data Fixtures ────────────────────────────────────────────────────

@pytest.fixture
def sample_events_raw():
    return pd.DataFrame([
        {
            "id": "evt1", "index": 0, "match_id": 1001, "player_id": 201,
            "player": "Messi", "team": "Barcelona", "team_id": 101,
            "type": "Pass", "period": 1, "minute": 10, "second": 5,
            "timestamp": "00:10:05.000",
            "location": [105.0, 35.0],
            "pass_end_location": [110.0, 38.0],
            "pass_length": 8.0, "pass_angle": 0.5,
            "pass_outcome": {"name": "Complete"},
            "pass_body_part": {"name": "Right Foot"},
            "under_pressure": True, "counterpress": False, "duration": 1.2,
        },
        {
            "id": "evt2", "index": 1, "match_id": 1001, "player_id": 202,
            "player": "Suarez", "team": "Barcelona", "team_id": 101,
            "type": "Shot", "period": 2, "minute": 55, "second": 30,
            "timestamp": "00:55:30.000",
            "location": [100.0, 38.0],
            "shot_outcome": {"name": "Goal"}, "shot_statsbomb_xg": 0.45,
            "shot_technique": {"name": "Normal"},
            "shot_body_part": {"name": "Right Foot"},
            "shot_end_location": [120.0, 38.0],
            "shot_type": {"name": "Open Play"},
            "under_pressure": False, "counterpress": True, "duration": 0.5,
        },
        {
            "id": "evt3", "index": 2, "match_id": 1001, "player_id": 201,
            "player": "Messi", "team": "Barcelona", "team_id": 101,
            "type": "Carry", "period": 1, "minute": 12, "second": 0,
            "timestamp": "00:12:00.000",
            "location": [90.0, 30.0],
            "carry_end_location": [100.0, 32.0],
            "under_pressure": False, "counterpress": False, "duration": 2.5,
        },
        {
            "id": "evt4", "index": 3, "match_id": 1001, "player_id": 203,
            "player": "Neymar", "team": "Barcelona", "team_id": 101,
            "type": "Dribble", "period": 1, "minute": 20, "second": 10,
            "timestamp": "00:20:10.000",
            "location": [95.0, 42.0],
            "dribble_outcome": {"name": "Complete"},
            "under_pressure": True, "counterpress": False, "duration": 1.0,
        },
    ])


@pytest.fixture
def sample_matches():
    return pd.DataFrame([
        {"match_id": 1001, "home_team": "Barcelona", "away_team": "Real Madrid",
         "home_score": 3, "away_score": 2, "match_date": "2015-11-01"},
        {"match_id": 1002, "home_team": "Barcelona", "away_team": "Atletico",
         "home_score": 2, "away_score": 1, "match_date": "2015-11-08"},
        {"match_id": 1003, "home_team": "Barcelona", "away_team": "Sevilla",
         "home_score": 4, "away_score": 1, "match_date": "2015-11-15"},
        {"match_id": 1004, "home_team": "Barcelona", "away_team": "Valencia",
         "home_score": 2, "away_score": 2, "match_date": "2015-11-22"},
        {"match_id": 1005, "home_team": "Barcelona", "away_team": "Sociedad",
         "home_score": 3, "away_score": 0, "match_date": "2015-11-29"},
    ])


@pytest.fixture
def sample_lineups():
    return pd.DataFrame([
        {"match_id": 1001, "player_id": 201, "player_name": "Messi",
         "team_name": "Barcelona",
         "positions": np.array([{"position": "Right Wing"}], dtype=object)},
        {"match_id": 1001, "player_id": 202, "player_name": "Suarez",
         "team_name": "Barcelona",
         "positions": np.array([{"position": "Center Forward"}], dtype=object)},
        {"match_id": 1001, "player_id": 203, "player_name": "Neymar",
         "team_name": "Barcelona",
         "positions": np.array([{"position": "Left Wing"}], dtype=object)},
    ])


@pytest.fixture
def sample_computed_features():
    return pd.DataFrame([
        {"match_id": 1001, "player_id": 201, "player_name": "Messi",
         "team_name": "Barcelona",
         "total_passes": 50, "complete_passes": 45, "progressive_passes": 12,
         "passes_under_pressure": 8, "avg_pass_length": 12.0,
         "pass_accuracy": 90.0,
         "total_shots": 4, "goals": 1, "shots_on_target": 3, "total_xg": 0.8,
         "avg_distance": 18.5, "shot_accuracy": 75.0, "xg_per_shot": 0.2,
         "xg_overperformance": 0.2,
         "avg_position_x": 85.0, "avg_position_y": 38.0,
         "std_position_x": 10.0, "std_position_y": 5.0,
         "position_deviation": 11.18, "attacking_tendency": 70.83,
         "total_pressures": 8, "avg_pressure_dur": 2.0, "total_pressure_dur": 16.0,
         "pressure_regains": 3, "pressing_efficiency": 37.5,
         "total_carries": 15, "total_carry_distance": 80.0,
         "avg_carry_distance": 5.33, "progressive_carries": 6,
         "total_dribbles": 5, "successful_dribbles": 4,
         "dribble_success_rate": 80.0,
         "total_actions": 80, "distance_covered": 300.0,
         "actions_p1": 45, "actions_p2": 35,
         "activity_drop_2nd_half": 22.22,
         "fouls_committed": 2, "fouls_won": 3, "yellow_cards": 1,
         "red_cards": 0, "ball_receipts": 40, "miscontrols": 2,
         "ball_retention_rate": 95.0,
         "vaep_rating": 0.85, "offensive_value": 0.6, "defensive_value": 0.25,
         "predicted_xg": 0.75},
        {"match_id": 1001, "player_id": 202, "player_name": "Suarez",
         "team_name": "Barcelona",
         "total_passes": 30, "complete_passes": 24, "progressive_passes": 5,
         "passes_under_pressure": 3, "avg_pass_length": 14.0,
         "pass_accuracy": 80.0,
         "total_shots": 6, "goals": 2, "shots_on_target": 4, "total_xg": 1.2,
         "avg_distance": 15.0, "shot_accuracy": 66.67, "xg_per_shot": 0.2,
         "xg_overperformance": 0.8,
         "avg_position_x": 88.0, "avg_position_y": 36.0,
         "std_position_x": 12.0, "std_position_y": 8.0,
         "position_deviation": 14.42, "attacking_tendency": 73.33,
         "total_pressures": 5, "avg_pressure_dur": 1.5, "total_pressure_dur": 7.5,
         "pressure_regains": 1, "pressing_efficiency": 20.0,
         "total_carries": 8, "total_carry_distance": 45.0,
         "avg_carry_distance": 5.63, "progressive_carries": 3,
         "total_dribbles": 3, "successful_dribbles": 2,
         "dribble_success_rate": 66.67,
         "total_actions": 55, "distance_covered": 200.0,
         "actions_p1": 30, "actions_p2": 25,
         "activity_drop_2nd_half": 16.67,
         "fouls_committed": 3, "fouls_won": 1, "yellow_cards": 0,
         "red_cards": 0, "ball_receipts": 25, "miscontrols": 3,
         "ball_retention_rate": 88.0,
         "vaep_rating": 0.75, "offensive_value": 0.55, "defensive_value": 0.20,
         "predicted_xg": 1.1},
        # Player 201 has 6 matches worth for advanced analysis
        {"match_id": 1002, "player_id": 201, "player_name": "Messi",
         "team_name": "Barcelona",
         "total_passes": 45, "complete_passes": 40, "progressive_passes": 10,
         "passes_under_pressure": 6, "avg_pass_length": 11.5,
         "pass_accuracy": 88.9,
         "total_shots": 3, "goals": 0, "shots_on_target": 2, "total_xg": 0.5,
         "avg_distance": 19.0, "shot_accuracy": 66.67, "xg_per_shot": 0.17,
         "xg_overperformance": -0.5,
         "avg_position_x": 82.0, "avg_position_y": 36.0,
         "std_position_x": 9.0, "std_position_y": 6.0,
         "position_deviation": 10.82, "attacking_tendency": 68.33,
         "total_pressures": 6, "avg_pressure_dur": 1.8, "total_pressure_dur": 10.8,
         "pressure_regains": 2, "pressing_efficiency": 33.3,
         "total_carries": 12, "total_carry_distance": 70.0,
         "avg_carry_distance": 5.83, "progressive_carries": 5,
         "total_dribbles": 4, "successful_dribbles": 3,
         "dribble_success_rate": 75.0,
         "total_actions": 75, "distance_covered": 280.0,
         "actions_p1": 40, "actions_p2": 35,
         "activity_drop_2nd_half": 12.5,
         "fouls_committed": 1, "fouls_won": 4, "yellow_cards": 0,
         "red_cards": 0, "ball_receipts": 35, "miscontrols": 1,
         "ball_retention_rate": 97.1,
         "vaep_rating": 0.72, "offensive_value": 0.50, "defensive_value": 0.22,
         "predicted_xg": 0.45},
        {"match_id": 1003, "player_id": 201, "player_name": "Messi",
         "team_name": "Barcelona",
         "total_passes": 48, "complete_passes": 43, "progressive_passes": 11,
         "passes_under_pressure": 7, "avg_pass_length": 12.2,
         "pass_accuracy": 89.6,
         "total_shots": 5, "goals": 2, "shots_on_target": 4, "total_xg": 1.0,
         "avg_distance": 17.5, "shot_accuracy": 80.0, "xg_per_shot": 0.2,
         "xg_overperformance": 1.0,
         "avg_position_x": 86.0, "avg_position_y": 37.0,
         "std_position_x": 11.0, "std_position_y": 5.5,
         "position_deviation": 12.3, "attacking_tendency": 71.67,
         "total_pressures": 7, "avg_pressure_dur": 2.1, "total_pressure_dur": 14.7,
         "pressure_regains": 3, "pressing_efficiency": 42.9,
         "total_carries": 14, "total_carry_distance": 78.0,
         "avg_carry_distance": 5.57, "progressive_carries": 6,
         "total_dribbles": 6, "successful_dribbles": 5,
         "dribble_success_rate": 83.3,
         "total_actions": 85, "distance_covered": 310.0,
         "actions_p1": 48, "actions_p2": 37,
         "activity_drop_2nd_half": 22.9,
         "fouls_committed": 1, "fouls_won": 2, "yellow_cards": 0,
         "red_cards": 0, "ball_receipts": 38, "miscontrols": 1,
         "ball_retention_rate": 97.4,
         "vaep_rating": 0.90, "offensive_value": 0.65, "defensive_value": 0.25,
         "predicted_xg": 0.95},
        {"match_id": 1004, "player_id": 201, "player_name": "Messi",
         "team_name": "Barcelona",
         "total_passes": 52, "complete_passes": 47, "progressive_passes": 13,
         "passes_under_pressure": 9, "avg_pass_length": 12.5,
         "pass_accuracy": 90.4,
         "total_shots": 6, "goals": 1, "shots_on_target": 3, "total_xg": 0.9,
         "avg_distance": 16.8, "shot_accuracy": 50.0, "xg_per_shot": 0.15,
         "xg_overperformance": 0.1,
         "avg_position_x": 84.0, "avg_position_y": 37.5,
         "std_position_x": 10.5, "std_position_y": 6.0,
         "position_deviation": 12.1, "attacking_tendency": 70.0,
         "total_pressures": 9, "avg_pressure_dur": 1.9, "total_pressure_dur": 17.1,
         "pressure_regains": 4, "pressing_efficiency": 44.4,
         "total_carries": 16, "total_carry_distance": 85.0,
         "avg_carry_distance": 5.31, "progressive_carries": 7,
         "total_dribbles": 5, "successful_dribbles": 4,
         "dribble_success_rate": 80.0,
         "total_actions": 88, "distance_covered": 320.0,
         "actions_p1": 50, "actions_p2": 38,
         "activity_drop_2nd_half": 24.0,
         "fouls_committed": 2, "fouls_won": 3, "yellow_cards": 0,
         "red_cards": 0, "ball_receipts": 42, "miscontrols": 2,
         "ball_retention_rate": 95.2,
         "vaep_rating": 0.78, "offensive_value": 0.55, "defensive_value": 0.23,
         "predicted_xg": 0.85},
        {"match_id": 1005, "player_id": 201, "player_name": "Messi",
         "team_name": "Barcelona",
         "total_passes": 48, "complete_passes": 44, "progressive_passes": 11,
         "passes_under_pressure": 7, "avg_pass_length": 12.1,
         "pass_accuracy": 91.7,
         "total_shots": 4, "goals": 1, "shots_on_target": 3, "total_xg": 0.6,
         "avg_distance": 17.2, "shot_accuracy": 75.0, "xg_per_shot": 0.15,
         "xg_overperformance": 0.4,
         "avg_position_x": 83.0, "avg_position_y": 37.0,
         "std_position_x": 10.2, "std_position_y": 5.8,
         "position_deviation": 11.7, "attacking_tendency": 69.2,
         "total_pressures": 7, "avg_pressure_dur": 2.0, "total_pressure_dur": 14.0,
         "pressure_regains": 3, "pressing_efficiency": 42.9,
         "total_carries": 13, "total_carry_distance": 72.0,
         "avg_carry_distance": 5.54, "progressive_carries": 5,
         "total_dribbles": 4, "successful_dribbles": 3,
         "dribble_success_rate": 75.0,
         "total_actions": 78, "distance_covered": 290.0,
         "actions_p1": 44, "actions_p2": 34,
         "activity_drop_2nd_half": 22.7,
         "fouls_committed": 1, "fouls_won": 2, "yellow_cards": 0,
         "red_cards": 0, "ball_receipts": 36, "miscontrols": 1,
         "ball_retention_rate": 97.2,
         "vaep_rating": 0.75, "offensive_value": 0.52, "defensive_value": 0.23,
         "predicted_xg": 0.55},
    ])


@pytest.fixture
def sample_scores():
    return pd.DataFrame([
        {"match_id": 1001, "player_id": 201, "player_name": "Messi",
         "team_name": "Barcelona",
         "position_group": "Attacker",
         "passing_score": 7.5, "shooting_score": 8.0,
         "positioning_score": 7.0, "pressing_score": 6.0,
         "movement_score": 7.5, "physical_score": 7.0,
         "behavioral_score": 8.0, "overall_score": 7.8,
         "vaep_rating": 0.85, "offensive_value": 0.6,
         "defensive_value": 0.25,
         "percentile_in_team": 85.0, "percentile_in_league": 78.0,
         "percentile_in_position": 80.0, "position_fit_score": 8.2,
         "performance_trend": "Improving",
         "player_cluster": "Creative Playmaker",
         "uuid": "abc-def"},
        {"match_id": 1001, "player_id": 202, "player_name": "Suarez",
         "team_name": "Barcelona",
         "position_group": "Attacker",
         "passing_score": 6.5, "shooting_score": 9.0,
         "positioning_score": 6.5, "pressing_score": 5.0,
         "movement_score": 6.0, "physical_score": 6.5,
         "behavioral_score": 7.0, "overall_score": 7.2,
         "vaep_rating": 0.75, "offensive_value": 0.55,
         "defensive_value": 0.20,
         "percentile_in_team": 70.0, "percentile_in_league": 65.0,
         "percentile_in_position": 72.0, "position_fit_score": 7.5,
         "performance_trend": "Stable",
         "player_cluster": "Target Forward",
         "uuid": "ghi-jkl"},
        {"match_id": 1002, "player_id": 201, "player_name": "Messi",
         "team_name": "Barcelona",
         "position_group": "Attacker",
         "passing_score": 7.2, "shooting_score": 6.5,
         "positioning_score": 6.8, "pressing_score": 5.5,
         "movement_score": 7.0, "physical_score": 6.8,
         "behavioral_score": 8.5, "overall_score": 7.0,
         "vaep_rating": 0.72, "offensive_value": 0.50,
         "defensive_value": 0.22,
         "percentile_in_team": 75.0, "percentile_in_league": 70.0,
         "percentile_in_position": 72.0, "position_fit_score": 7.8,
         "performance_trend": "Stable",
         "player_cluster": "Creative Playmaker",
         "uuid": "mno-pqr"},
        {"match_id": 1003, "player_id": 201, "player_name": "Messi",
         "team_name": "Barcelona",
         "position_group": "Attacker",
         "passing_score": 8.0, "shooting_score": 9.0,
         "positioning_score": 7.5, "pressing_score": 6.5,
         "movement_score": 8.0, "physical_score": 7.2,
         "behavioral_score": 8.5, "overall_score": 8.5,
         "vaep_rating": 0.90, "offensive_value": 0.65,
         "defensive_value": 0.25,
         "percentile_in_team": 95.0, "percentile_in_league": 92.0,
         "percentile_in_position": 93.0, "position_fit_score": 9.0,
         "performance_trend": "Improving",
         "player_cluster": "Creative Playmaker",
         "uuid": "stu-vwx"},
        {"match_id": 1004, "player_id": 201, "player_name": "Messi",
         "team_name": "Barcelona",
         "position_group": "Attacker",
         "passing_score": 7.8, "shooting_score": 7.5,
         "positioning_score": 7.2, "pressing_score": 6.2,
         "movement_score": 7.6, "physical_score": 7.1,
         "behavioral_score": 8.2, "overall_score": 7.6,
         "vaep_rating": 0.78, "offensive_value": 0.55,
         "defensive_value": 0.23,
         "percentile_in_team": 82.0, "percentile_in_league": 80.0,
         "percentile_in_position": 81.0, "position_fit_score": 8.0,
         "performance_trend": "Stable",
         "player_cluster": "Creative Playmaker",
         "uuid": "yza-bcd"},
        {"match_id": 1005, "player_id": 201, "player_name": "Messi",
         "team_name": "Barcelona",
         "position_group": "Attacker",
         "passing_score": 7.6, "shooting_score": 7.0,
         "positioning_score": 7.1, "pressing_score": 5.8,
         "movement_score": 7.2, "physical_score": 6.9,
         "behavioral_score": 8.3, "overall_score": 7.4,
         "vaep_rating": 0.75, "offensive_value": 0.52,
         "defensive_value": 0.23,
         "percentile_in_team": 80.0, "percentile_in_league": 75.0,
         "percentile_in_position": 78.0, "position_fit_score": 7.9,
         "performance_trend": "Stable",
         "player_cluster": "Creative Playmaker",
         "uuid": "efg-hij"},
        {"match_id": 1006, "player_id": 201, "player_name": "Messi",
         "team_name": "Barcelona",
         "position_group": "Attacker",
         "passing_score": 7.3, "shooting_score": 7.8,
         "positioning_score": 6.9, "pressing_score": 6.0,
         "movement_score": 7.4, "physical_score": 7.0,
         "behavioral_score": 8.1, "overall_score": 7.5,
         "vaep_rating": 0.80, "offensive_value": 0.58,
         "defensive_value": 0.22,
         "percentile_in_team": 83.0, "percentile_in_league": 79.0,
         "percentile_in_position": 80.0, "position_fit_score": 8.1,
         "performance_trend": "Stable",
         "player_cluster": "Creative Playmaker",
         "uuid": "hij-klm"},
    ])


@pytest.fixture
def sample_spadl():
    return pd.DataFrame([
        {"match_id": 1001, "player_id": 201, "player_name": "Messi",
         "team_name": "Barcelona", "event_index": 1,
         "type_name": "pass", "result_name": "success",
         "bodypart_name": "foot",
         "start_x": 105.0, "start_y": 35.0, "end_x": 110.0, "end_y": 38.0,
         "period_id": 1, "time_seconds": 605, "under_pressure": 1},
        {"match_id": 1001, "player_id": 202, "player_name": "Suarez",
         "team_name": "Barcelona", "event_index": 2,
         "type_name": "shot", "result_name": "success",
         "bodypart_name": "foot",
         "start_x": 100.0, "start_y": 38.0, "end_x": 120.0, "end_y": 38.0,
         "period_id": 2, "time_seconds": 3330, "under_pressure": 0},
    ])


@pytest.fixture
def sample_shots():
    return pd.DataFrame([
        {"event_id": "s1", "match_id": 1001, "player_id": 202,
         "player_name": "Suarez",
         "location_x": 100.0, "location_y": 38.0,
         "distance_to_goal": 20.59, "angle_to_goal": 0.39,
         "shot_technique": "Normal", "bodypart": "Right Foot",
         "under_pressure": 0, "shot_after_set_piece": 0,
         "shot_outcome": "Goal", "shot_xg": 0.45, "is_goal": 1},
        {"event_id": "s2", "match_id": 1001, "player_id": 201,
         "player_name": "Messi",
         "location_x": 95.0, "location_y": 42.0,
         "distance_to_goal": 25.12, "angle_to_goal": 0.52,
         "shot_technique": "Volley", "bodypart": "Left Foot",
         "under_pressure": 1, "shot_after_set_piece": 0,
         "shot_outcome": "Off Target", "shot_xg": 0.12, "is_goal": 0},
    ])


@pytest.fixture
def sample_events_for_api():
    return pd.DataFrame([
        {"match_id": 1001, "event_id": "e1", "player_id": 201,
         "player_name": "Messi", "team_name": "Barcelona",
         "event_type": "Pass",
         "minute": 10, "period": 1,
         "location_x": 105.0, "location_y": 35.0,
         "pass_outcome": "Complete", "shot_outcome": None,
         "shot_xg": None, "uuid": "abc"},
    ])


@pytest.fixture
def mock_data_dict(sample_scores, sample_computed_features, sample_matches,
                   sample_events_for_api):
    return {
        "events": sample_events_for_api,
        "computed": sample_computed_features,
        "scores": sample_scores,
        "vaep": pd.DataFrame({"match_id": [1001, 1001], "player_id": [201, 202],
                              "vaep_rating": [0.85, 0.75]}),
        "matches": sample_matches,
        "lineups": pd.DataFrame(),
        "bench": pd.DataFrame({"position_group": ["Attacker", "Midfielder", "Defender", "GK"],
                                "pass_accuracy": [85.0, 80.0, 75.0, 70.0],
                                "total_actions": [60.0, 70.0, 65.0, 30.0]}),
        "weights": {
            "Attacker": {"passing_score": 0.15, "shooting_score": 0.30,
                         "positioning_score": 0.20, "pressing_score": 0.10,
                         "movement_score": 0.10, "physical_score": 0.08,
                         "behavioral_score": 0.07},
            "Midfielder": {"passing_score": 0.28, "shooting_score": 0.12,
                           "positioning_score": 0.18, "pressing_score": 0.18,
                           "movement_score": 0.12, "physical_score": 0.07,
                           "behavioral_score": 0.05},
            "Defender": {"passing_score": 0.18, "shooting_score": 0.05,
                         "positioning_score": 0.25, "pressing_score": 0.22,
                         "movement_score": 0.10, "physical_score": 0.12,
                         "behavioral_score": 0.08},
            "GK": {"passing_score": 0.20, "shooting_score": 0.02,
                   "positioning_score": 0.30, "pressing_score": 0.15,
                   "movement_score": 0.08, "physical_score": 0.15,
                   "behavioral_score": 0.10},
        },
    }


@pytest.fixture
def client(mock_data_dict):
    with patch("api.routes._shared._load_data", return_value=mock_data_dict):
        from api.main import app
        app.dependency_overrides = {}
        with TestClient(app) as c:
            yield c


@pytest.fixture
def clean_events(sample_events_raw):
    from pipeline.data_loader import clean_events as ce
    return ce(sample_events_raw)
